In [ ]:
# 가장 가까운 같은 글자
def solution(s):
  answer=[]
  for i in range(len(s)):
    check=s[:i]
    check=''.join(check[::-1]) # 문자열 뒤집기
    index=check.find(s[i])+1 # 문자열 중 char 위치 찾기
    if index==0:
      index=-1
    answer.append(index)

  return answer

In [ ]:
# 실패율
def solution(N,stages):
  answer=[]
  deno=len(stages)
  for i in rnage(1,N+1):
    if deno !=0:
      num=stages.count(i)
      answer.append([i,num/deno])
      deno-=num
    else:
      answer.append([i,0])

  answer=sorted(answer,key=lambda x:(x[1],-x[0]),reverse=True) # value를 우선으로 정렬 후 같다면 key의 역순으로 정렬렬
  answer=[i[0] for i in answer] # key만 뽑아서 list 만들기기
  return answer

In [ ]:
# 약수의 개수 구하기
def solution(number, limit, power):
  answer=0
  check=[]
  confirm=[]
  for i in range(1, number+1):
    cnt=0
    confirm.clear()
    for j in range(1, int(i**(1/2)+1)):
      if i%j==0:
        confirm.append(j)
        if (j**2)!=i:
          confirm.append(i//j)
    check.append(len(confirm))

  return check

In [ ]:
# 키패드 누르기(거리 구하기, xy축)
def getLength(hand, i):
    keypad = {1:[0,0], 2:[1,0], 3:[2,0],
              4:[0,1], 5:[1,1], 6:[2,1],
              7:[0,2], 8:[1,2], 9:[2,2],
            '*':[0,3], 0:[1,3], '#':[2,3]}
    
    x_hand, y_hand = keypad[hand]
    x_num, y_num = keypad[i]
    
    return abs(x_hand-x_num)+abs(y_hand-y_num)

In [ ]:
# BFS, 만들 수 있는 수 모두 구한 후, 조건에 부합하면 +1
def solution(numbers, target):
    answer = 0
    check=[0]
    for i in numbers:
        tmp=[]
        for j in check:
            tmp.append(j+i)
            tmp.append(j-i)
        check=tmp
    for i in check:
        if i ==target:
            answer+=1
    return answer

In [ ]:
# 게임 맵 최단거리 구하기(queue 사용, DFS)
from collections import deque
def solution(maps):
    answer = 0
    dx,dy=[-1,1,0,0],[0,0,-1,1]
    q=deque([(0,0)])
    
    visit=[[0]*len(maps[0]) for _ in range(len(maps))]
    visit[0][0]=1
    maps[0][0]=0
    
    while q:
        x,y=q.popleft()
        for k in range(4):
            nx,ny=x+dx[k], y+dy[k]
            if 0<=nx<len(maps) and 0<=ny<len(maps[0]):
                if maps[nx][ny]==1 and not visit[nx][ny]:
                    visit[nx][ny]=visit[x][y]+1
                    q.append((nx,ny))
    answer=-1
    if visit[-1][-1]:
        return visit[-1][-1]
    return answer

MySQL

1. NULL인 값을 변경하여 SELECT

SELECT IFNULL(NAME, "No name") AS 'NAME'

SELECT COALESCE(NAME,'No name')


2. 최댓값을 구하기

SELECT * 

FROM FOOD

WHERE PRICE=(SELECT MAX(PRICE)

              FROM FOOD
              )

SELECT *

FROM FOOD

ORDER BY PRICE DESC

LIMIT 1


3. DATEFORMAT 관련

SELECT DATE_FORMAT(DATETIME, '&Y-%m-%d') AS '날짜'


4. CASE WHEN 구문

SELECT ANIMAL_ID,

  CASE WHEN INTAKGE LIKE '%Neutered'

  THEN 'O' ELSE 'X' END AS '중성화'


5. HOUR 관련

SELECT HOUR(DATETIME) AS "HOUR", COUNT(DATETIME) AS "COUNT"

FROM ANIMAL

GROUP BY HOUR(DATETIME)

HAVING HOUR>=9 AND HOUR<=19

ORDER BY HOUR


6. 코드 생성

SELECT LEFT(PRODUCT_CODE, 2) AS CATEGORY, COUNT (*) AS 'PRODUCTS'

FROM PRODUCT

GROUP BY LEFT(PRODUCT_CODE, 2)

ORDER BY LEFT(PRODCUT_CODE, 2)



7. WHERE 절에 NOT IN

WHERE ANIMAL_ID NOT IN 

(

  SELECT ANIMAL_ID

  FROM ANIMAL_OUTS

)


8. 두 개의 테이블에서 SUM

 SELECT A.PRODUCT_CODE, SUM(A.PRICE*B.SALES_AMOUNT) AS SALES

 
9. CASE WHEN (2)

SELECT ID,

  CASE WHEN DATE<='2022-05-01'

    THEN '출고완료'

  WHEN DATE>'2022-05-01'

    THEN '출고대기'

  ELSE '출고 미정'

  END AS 출고여부


10. 1000단위로 범위 쪼개기


SELECT truncate(price, -4) as PRICE_GROUP, COUNT (*) AS PRODUCTS

FROM PRODUCT

GROUP BY PRICE_GROUP